### ISSUE TITLE
Demo of CI-CD pipeline

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#128]

**Comment by ayishacs** [comment]
- [ ] Demo of end to end CI-CD build pipeline
- [ ] Project Management

**Comment by visheshdembla** [comment]
Since I primarily developed the complete CI for 5 microservices, it makes sense that I take up this task. Hence, picking up.

**Comment by visheshdembla** [comment]
Closing as the presentation part of this is already complete.
