### ISSUE TITLE
Mid term Presentation Task for Vishesh

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#129]
Presentation Slides for below:

- [ ] Programming Languages 
- [ ] Third party tools and services
- [ ] Task Distribution

**Comment by visheshdembla** [comment]
I am not clear what needs to be done in this. Could you please elaborate what is the expectation?

**Comment by visheshdembla** [comment]
I would be working on the CI CD part of the presentation and not the topics described in the description. The preparation is done so closing the issue.
