### ISSUE TITLE
Integrating scm, circleci and aws 

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#144]
This task is  created for CI-CD demo.

**Comment by visheshdembla** [comment]
Since this task was not discussed with the team, closing the item. Also we are not using AWS ECR as we already are on Docker Hub. Please communicate well with Suraj and Me before randomly creating tasks. 

Closing the item. 

Feel free to discuss in the next team meeting and re-open the item.

**Comment by ayishacs** [comment]
The current update on task we have CI setup and not CD setup for demo. So re-opening this issue and will add further details in the upcoming threads.

**Comment by visheshdembla** [comment]
please make sure that the description of your issue reflects what you are working on. If you are wokring on the presentation under this issue, please mention it so. Renaming the issue.

**Comment by visheshdembla** [comment]
Since the clear guidance from the teachers was not to use AWS, please kindly close the issue and maintain clear transparency with the team about what you are working on as we would not be able to justify what the team worked on that was actually asked from the team.

**Comment by ayishacs** [comment]
![ci-cd](https://user-images.githubusercontent.com/77846296/111577756-4c947880-8789-11eb-8d2c-1791758a20a4.png)

The above setup was created as part of CI-CD Midterm Demo
