### ISSUE TITLE
Implement CI and Dockerfile for session-log-service

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#149]
Need to write a Dockerfile and CI setup for the session-log-service.

**Comment by ayishacs** [comment]
@visheshdembla 
Please use the below port for containerizing the app. 
session-log-service  - 50065

This is to avoid port conflict at the time of kubernetes deployment.
It was observed that multiple applications were assigned the same port

More details could be found in the below issue
https://github.com/airavata-courses/Panorama/issues/153

**Comment by visheshdembla** [comment]
Closing as implementation is done.
