### ISSUE TITLE
Minikube installation and setup to test kubernetes deployment

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#159]
Key points :
1. Setup minikube 
2. Deploy an application 
3. Test the service

**Comment by ayishacs** [comment]
MInikube installation has been completed on local ubuntu machine since access to Jetstream VMs are awaited.
![image](https://user-images.githubusercontent.com/77846296/111712948-055bc580-8825-11eb-98ac-827c5d797744.png)

**Comment by ayishacs** [comment]
Fixed proxy issue to access dashboard.
minikube dashboard is up and running.
![image](https://user-images.githubusercontent.com/77846296/111774167-7d59d800-8885-11eb-9969-9e5f67660a11.png)

**Comment by ayishacs** [comment]
Successfully tested kubernetes deployments of the following applications on local minikube setup:
react-ui 
gateway service
image service

![image](https://user-images.githubusercontent.com/77846296/111798680-af2c6800-88a0-11eb-910d-118fabb655b9.png)

**Comment by ayishacs** [comment]
Successfully tested kubernetes deployments of the all the applications committed at this time:
auth-service
session-service
user-service
image-service
gateway-service
reactui

![image](https://user-images.githubusercontent.com/77846296/111835073-dbf57500-88ca-11eb-96a1-d9d47bc5ed7c.png)

**Comment by ayishacs** [comment]
Pods are successfully running for the following applications:
auth-service
session-service
user-service
image-service
gateway-service
reactui

![image](https://user-images.githubusercontent.com/77846296/111836605-f3356200-88cc-11eb-9ca2-fa5b2bbe3517.png)

**Comment by ayishacs** [comment]
Pods are succesfully running for each of the application

![image](https://user-images.githubusercontent.com/77846296/111836146-3b07b980-88cc-11eb-875c-660842eee054.png)

**Comment by surajp28** [comment]
Amazing work @ayishacs. If I am not wrong, we would only have to add the database config for each service now since the services are up and running?

**Comment by surajp28** [comment]
Task Update: Minikube installation done. @ayishacs Your committed files were helpful. Thank you.
![image](https://user-images.githubusercontent.com/64825150/111885969-5395d380-89a1-11eb-8718-85a72a1c129d.png)
Pending: Linking services to data bases

**Comment by ayishacs** [comment]
@surajp28. Inter service communication would be the consecutive step.  
we will test the microservice and db connections in the next step.

**Comment by ayishacs** [comment]
@surajp28 @visheshdembla 
We shall update this list to keep data about inter service communication documented, which would eventually help us for establishing network and hence the connections between microservices while deploying them on pods
Here is a consolidated list of inter-service communications:
 Auth-service => MongoDB
 Auth-service => Session service
 Gateway-service => Auth-service
 Gateway-service => Image-service
 Gateway-service => SessionLog-Service
 Gateway-service => Session-service
 Gateway-service => User-service

**Comment by visheshdembla** [comment]
The list is incomplete right now. We have database connections also from user service as well as session-log service. The image service uses a database as well, however since it is sqlite, it is local right now, which needs to be replaced with Postgres, which would again be a communication.

**Comment by ayishacs** [comment]
Closing this issue as minikube setup is complete
