### ISSUE TITLE
create mockup for login page

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#16]
create a UI mockup for the login page using Adobe XD based on the pen-paper diagram in #3

**Comment by surajp28** [comment]
![login](https://user-images.githubusercontent.com/64825150/107135601-0d415500-68ca-11eb-8ec6-4ef1b0b4fa66.png)

**Comment by visheshdembla** [comment]
Looks good. I think we have a consistent theme across the UIs that we have developed till now
