### ISSUE TITLE
Launch VMs in Jetstream cloud to launch kubernetes cluster

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#161]
The issue is created to accomplish following tasks:
1. Launch linux VM in atmosphere
2. Install openstack command line utilities
3. Configure openrc
4. Launch 3 VMs on openstack cloud
    Kubernetes-master
    Kubernetes-node1
    Kubernetes-node2

**Comment by ayishacs** [comment]
Task status update:
1. Launch linux VM in atmosphere - Completed
![image](https://user-images.githubusercontent.com/77846296/111909595-4d9d0280-8a34-11eb-8844-2602ae31251e.png)

**Comment by ayishacs** [comment]
Task status update:   

2.  Install openstack command line utilities - Completed
3.  Configure openrc.sh - Completed

    
![image](https://user-images.githubusercontent.com/77846296/111909786-02cfba80-8a35-11eb-8602-58a9121f352c.png)

**Comment by ayishacs** [comment]
Task status update:

   4. Launch 3 VMs using openstack command line utilities on IU cloud for kubernetes cluster - Completed
   
![image](https://user-images.githubusercontent.com/77846296/111909970-c05aad80-8a35-11eb-8075-6fca2c24ea31.png)

**Comment by ayishacs** [comment]
Task is successfully completed

**Comment by Arjunbhavsar** [comment]
The steps seem correct till now, You can start working on setting up the cluster over these VM's
