### ISSUE TITLE
create a mockup for signup page

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#17]
create a UI mockup for the sign up page using Adobe XD based on the pen-paper diagram in #3

**Comment by surajp28** [comment]
![sign_up](https://user-images.githubusercontent.com/64825150/107135611-23e7ac00-68ca-11eb-9186-c09060dc738f.png)

**Comment by visheshdembla** [comment]
seems good. Consistent with our theme as well.
