### ISSUE TITLE
create a mockup for Photos page with some pictures selected

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#19]
create a UI mockup for the picture selected photos page using Adobe XD based on the pen-paper diagram in #3

**Comment by surajp28** [comment]
![Panorama_Selected](https://user-images.githubusercontent.com/64825150/107135626-4aa5e280-68ca-11eb-8826-6ed680fa75db.png)

**Comment by visheshdembla** [comment]
Looks good 👍
