### ISSUE TITLE
Give access to public key to connect to kubernetes cluster

### ISSUE THREAD

**Issue by surajp28** [airavata-courses/Panorama#193]
Hi @ayishacs ,
I have create a new public private rsa key and would like to access the cluster via them
I have sent you my latest public key. Can you grant permission for the same.
Kindly try to pick this up on an urgent basis since I cannot proceed further.

**Comment by ayishacs** [comment]
@surajp28 .. I had added the public keys provided by you twice before. Please check you should be able to access by both of the previous provided key pair. Also let me know if you need further help.

**Comment by surajp28** [comment]
For this key -

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCik3HqsKLV+GdtgWkQHgLV9Xr158v6hu9jEvcTDCWdg1UNZpQQ7RPXcuGIGFLdsVSMOHuXhAB9QJIQSnTWdBIKhS1Ed4cBBzQfobNhG5m+8LvqAW3+AjtSgI7D3b44kYY9dIa4HkUg64jHllxA27zUXSQ0w1y+wqcLHLNNspGFUJH/UXDWQYoNpd8ZYe5qbqTZBpW7UBHM4BvBXdZYCRjI8bG2hWuh115W9bZdSrWxSW9P7DcEkgmGhmsEyvmGlZMl9f8mmKigqALOVPVjd6vufmu7HiVostSge8eKYacAGEDfUca1cFssCKRux9ufEk2upSWvpkmpyEimycVCzeKhrq2/v6k0/3nscu3JeC1c2tjX8uwbvUsHTxZlBM0/JTFbGNaWNHUBb0gy+naoefaXoMb643inu+X3dmoK6dgb4ZBweOqDCd9nv7j96v84MTnlWcKxfqkr5SYfWL0Ny5oPPxsvZf7ipA1vtz9Ex3VlHnzaLkqdwMHeKJPb4XZemUs= surajpunjabi

I get permission denied when I try to access with my private key. Could you confirm and check if this is the same key you have given me access for

**Comment by ayishacs** [comment]
All the keys that were provided on slack have been authorized as discussed.
Closing this issue
