### ISSUE TITLE
JMeter Setup for Load Testing

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#198]
The issue is created to setup JMeter and test the load handling capacity of running pods and services.

Perform the following tests by incrementing the replica count and plot the graphs accordingly.

1. Analyze the response times of the application by incrementing the pod capacity.
2. Analyze the peak load for the application.

**Comment by ayishacs** [comment]
**Analysis of Response times vs Incremental Capacity** 

Pod count: 1
Number of concurrent users: 1000
![image](https://user-images.githubusercontent.com/77846296/114740822-33df9a00-9d18-11eb-8794-47edb20cb309.png)

**Comment by ayishacs** [comment]
Pod count: 2
Number of concurrent users: 1000

![image](https://user-images.githubusercontent.com/77846296/114741009-5d98c100-9d18-11eb-94a2-0962e147d087.png)

**Comment by ayishacs** [comment]
Pod count: 3
Number of concurrent users: 1000

![image](https://user-images.githubusercontent.com/77846296/114741159-7dc88000-9d18-11eb-9491-f97355c25d80.png)

**Comment by ayishacs** [comment]
Pod count: 4
Number of concurrent users: 1000

![image](https://user-images.githubusercontent.com/77846296/114742389-b2890700-9d19-11eb-921e-6fe9b04778c3.png)

**Comment by visheshdembla** [comment]
Hi @ayishacs , 
could you clarify for what requests are the graphs generated? 
Also can you please upload the scripts in the repo in some branch.
Since the integration of the services was just completed now on a different cluster, I don't know if these results are valid or not. Could you please also provide some clarification on the same?

**Comment by visheshdembla** [comment]
Meanwhile I believe @surajp28 is working on JMeter scripts for functionalities in the backend. Could you please sync with him on what you've covered and take it from there?

**Comment by ayishacs** [comment]
@visheshdembla @surajp28 
The graphs are generated for the UI. We will have to continue our load and spike tests for API and other Microservices.
The script will be committed to github after completing the integration tests for all the services.
Let us schedule a call to run the load, spike and fault tolerance tests .

**Comment by surajp28** [comment]
A folder for JMX testing has been created. The script and results are have been uploaded as well. Kindly go through them.
The following partner has been observed
100 users with 100 data entries
100 users with 500 data entries
100 users with 1000 data entries
100 users with 10000 data entries

500 users with 500 data entries
500 users with 1000 data entries
500 users with 1000 data entries

1000 users with 1000 data entries
1000 users with 10000 data entries

10000 users with 10000 data entries

I would upload the login functionality soon

**Comment by surajp28** [comment]
Login functionality added as well

**Comment by visheshdembla** [comment]
Fixed issues in image service and other microservices to ensure load testing works.

**Comment by surajp28** [comment]
The load testing for signin, signup, image store and image retrieval has been completed. It shall be updated to the wiki shortly
