### ISSUE TITLE
Investigating network and dns on kubernetes cluster 

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#199]
Interservice communication issue resolution scenarios

**Comment by ayishacs** [comment]
The cluster IPs for coredns, UI are in different IP range relative to backend. 
Working on this issue to see if it is impacting inter service communication.

![image](https://user-images.githubusercontent.com/77846296/114440421-1d123980-9b98-11eb-98ff-a42e10470884.png)

@surajp28 @visheshdembla 
Please feel free to add your inputs and findings

**Comment by ayishacs** [comment]
Mitigation steps:
Kubernetes cluster was reset. 
Kubernetes cluster has been redeployed - all the microservices are within the same cluster IP range.
![image](https://user-images.githubusercontent.com/77846296/114471424-9d4b9580-9bbe-11eb-9aa5-71efc4ca4523.png)

**Comment by ayishacs** [comment]
Closing this issue.

**Comment by visheshdembla** [comment]
The issue with the original setup could not be resolved. Based on investigations, we figured out that the issue was due to some network related issue during the setup. So we have gone ahead and created a new setup where everything is working as expected. Hence closing the issue for good now.

**Comment by ayishacs** [comment]
All of the VMs were created within the same subnet and the pods hosting microservices in containers are within the same cluster IP range as seen in the previous screenshot. Hence it is clear that the issue is not at the network level.
