### ISSUE TITLE
create flow chart for information architecture

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#2]
@visheshdembla @surajp28 @ayishacs
#First deliverable
Task2: Flow chart for information architecture
Update Readme.md

**Comment by visheshdembla** [comment]
Here are the drafts for the Flow Diagram.
I am also creating a branch and pushing the same there.

![user-flow-Download Photos](https://user-images.githubusercontent.com/13031482/106820783-f5f43480-6649-11eb-881a-cb3e7d685182.png)
![user-flow-Login](https://user-images.githubusercontent.com/13031482/106820785-f5f43480-6649-11eb-8e4c-8644d995713e.png)
![user-flow-Share Photos](https://user-images.githubusercontent.com/13031482/106820786-f68ccb00-6649-11eb-9227-35e3a4e87fbd.png)
![user-flow-Upload Photos](https://user-images.githubusercontent.com/13031482/106820787-f68ccb00-6649-11eb-8973-b7319aa5c134.png)
![user-flow-View Photos](https://user-images.githubusercontent.com/13031482/106820788-f68ccb00-6649-11eb-8317-a1913dee4c5b.png)

**Comment by visheshdembla** [comment]
@ayishacs @surajp28 please review the same and provide your feedbacks.
The branch name for the same is flow-diagrams.

**Comment by visheshdembla** [comment]
closing since there is no feedback. please re-open if there is some additional feedback on the same.
