### ISSUE TITLE
create a mockup for account overview page

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#20]
create a UI mockup for the account overview page using Adobe XD based on the pen-paper diagram in #3

**Comment by ayishacs** [comment]
![AccountOverview](https://user-images.githubusercontent.com/77846296/107157128-ff321980-6947-11eb-9843-45284d47d3fe.JPG)

**Comment by ayishacs** [comment]
Here is the mock-up for account overview. @visheshdembla @surajp28 
Please review and add your feedback. I will be creating the pull request for the same.

**Comment by visheshdembla** [comment]
Doesn't make sense to have the photos again on the Account overview page since we have them already at the view photos page. Just the information on the left side of the page would have been enough.

**Comment by ayishacs** [comment]
Given an account overview page is the window to user activity. And having referred popular photo-sharing apps. I felt its relevant to include photos section. But I will reduce the number of photos and include one more section which would give us an overview of users with whom the photos have been shared.
