### ISSUE TITLE
Spike Testing

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#201]
Spike Testing involves increasing the load on the system suddenly and observing the behaviour of the system. 
Need to invest in understanding how this would be achieved.

**Comment by ayishacs** [comment]
The goal of spike testing is to analyze the behavior of a software application when it receives extreme variations in traffic. Spike testing helps us understand an application's maximum load; it also verifies an application's recovery time between activity spikes. We can test this by setting a constant pod count. By hitting the pods with high load such as 10000, 15000, 20000 concurrent threads , we have to make a note about the actual frequency at which spikes are observed. This helps us plan and determine the infrastructure capacity during sales day such as black friday and cyber monday.

**Comment by visheshdembla** [comment]
please provide with updates on the spike testing as it has been two days since the last update. @ayishacs

**Comment by ayishacs** [comment]
The following observations have been made while spike testing panorama application:
1. Performed a spike test by simulating large number of users via thread groups for a duration of 2 hours to analyze the system behavior under extreme load.
2. The simulated traffic was hit on the services of panorama application and steep spikes were observed in response times with the variations of traffic over time. 
3. Observed considerable latency, reduced throughout and increase in error rate while analyzing the response for requests with time and incremental load.

This thread will be updated with further observations

**Comment by ayishacs** [comment]
The above observation was made for gateway wherein the error rate is 100%, which means the test is invalid.
Ignore the previous results and performing stress testing again along with troubleshooting build failures for ui in jenkins

**Comment by visheshdembla** [comment]
Completed spike testing 
https://github.com/airavata-courses/Panorama/pull/214/commits/377cdcc872c3b8c92f2425419d1a8d94a9566cf9

**Comment by ayishacs** [comment]
Adding spike testing results with 10000 concurrent users for the application
![TimevsThreads10000concurrentusers](https://user-images.githubusercontent.com/77846296/116733038-98a62000-a9b9-11eb-8414-0811f87504b0.JPG)
![ResponseTimeOverview10000concurrentusers](https://user-images.githubusercontent.com/77846296/116733090-a8256900-a9b9-11eb-9596-2387b20aca08.JPG)

**Comment by ayishacs** [comment]
![LatencyvsRequest10000ConcurrentThreadsOverTime](https://user-images.githubusercontent.com/77846296/116733139-ba9fa280-a9b9-11eb-80de-9e13637a6bdf.JPG)
