### ISSUE TITLE
Configure NGINX for Blue-Green Deployment

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#215]
Configure NGINX with the deployment to route traffic between the two deployments

**Comment by visheshdembla** [comment]
Added NGINX to the UI. The logic to load balance can be added to the UI. Since we only need to load balance two services, that are the gateway services of the application, we can do that directly using NGINX.

**Comment by visheshdembla** [comment]
Completed load balancing for green blue deployment. 
In normal working scenarios, the requests are balanced across the services in a round robin fashion. Since the services are stateless in nature, the requests are processed properly without any issues.

In case one of the cluster goes down, the request is redirected to the other server.

https://github.com/airavata-courses/Panorama/commit/9b41c9aabf9c868d1bce90d7d1d647e0a5764e8a

**Comment by surajp28** [comment]
The load-balancing was shown as part of the end-term presentations where the services were working in spite of a cluster being down.

**Comment by surajp28** [comment]
Also, as mentioned in the presentations, the initial approach was to go with Istio. However, due to configuration issues, we went with nginx
