### ISSUE TITLE
create a UI mockup for the download dialog

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#22]
create a UI mockup for the download dialog using Adobe XD

**Comment by visheshdembla** [comment]
uploaded mockups for download dialog

**Comment by visheshdembla** [comment]
closing as the mockup is created and added to wiki

**Comment by ayishacs** [comment]
![download](https://user-images.githubusercontent.com/77846296/107160370-6dcca280-695b-11eb-89da-8c796a01bcbd.JPG)

@visheshdembla @surajp28 
Please review the download dialog for the Application

**Comment by visheshdembla** [comment]
Please review the following points
A. The download is supposed to be a dialog not a separate page, as we had discussed in the meetings and the issue reflects the same.
B. Similar to the upload page, this page doesn't follow the template that we have for the rest of our UI UX
C. We only have IU cloud storage so the options for other cloud storages like One Drive are redundant.
D. I don't understand the point of representing the Authenticated User here as it is a UI mockup and only users who are Authenticated would be able to see this.

**Comment by visheshdembla** [comment]
Please do the needful @ayishacs

**Comment by ayishacs** [comment]
Thank you for your valuable feedback @visheshdembla 

Please find my inputs regarding the same:

1) Addressing point A and B,

I am sharing a few references for the individual upload and download pages of popular photo-sharing applications, It need not necessarily be the dialogue box.

![individual download page example 2](https://user-images.githubusercontent.com/77846296/107161847-0582be80-6965-11eb-8c00-6ef6c8c3ca99.JPG)
![instagram download page](https://user-images.githubusercontent.com/77846296/107161849-07e51880-6965-11eb-81eb-32c99b0daed3.JPG)

2) At this point, we do not have details as to which IU cloud storage we will be using in the project. It is for respresentation purpose only

3) Regarding point 4, it is quite common to show up the authenticated user's name and profile in file sharing and photo sharing applications such as facebook, instagram, google docs and so on.

4) I had a look of the wireframes and as suggested, the mock-ups pages aren't good enough, where we the icon size are mismatched with textual data.

**Comment by visheshdembla** [comment]
1. Again I clearly understand that I doesn't need to be a dialog box, but that is what we had decided in the meeting and that's why everything else from sharing photos, to creating album is also a dialog. So either you can make the download option a dialog or please feel free to change the share page along with the create album page as well. I don't have an issue with either a dialog or a page, but since in the meeting, we had decided that it would be a dialog, I assumed that it should be a dialog. 

If you like pages more over dialog, please convert the Share Dialog to a share page and the Create Album Dialog to Create Album Page which look similar to this.

The point is to have a consistent UX, not whether options should be dialogs or pages.

2. Coming to the second point, IU has box and drive storages, and representing any one of them would be fine. The mockups are just a representation, we can obviously show that IU storage is represented by Drive and later change it to Box or something. But there needs to be just one single option representing the IU storage and not multiple. That is the point that I am trying to make here. 

3. Again, I understand it is common to show the authenticated user's profile picture, but the photos are usually at the top left or top right corner and not placed randomly anywhere. Also it's not about having the profile picture. It doesn't make sense to have the profile picture of the user in the middle of the download page and not say on the upload page, the share page, the create album page, etc. Every other mockup that the team has created has the user photo at the top left corner. I think if we represent the user profile picture on the right here, we would need to change the same on every mockup that we have created. So I believe it is easier to change one that to change all, hence the suggestion.

4. Regarding the fourth point, the base wireframe that @surajp28 created is just a positional representation of how our UI would look and where the icons would be with regards to the navigation bar and the other options. The other UIs like say the Create Album and the share photos, have just used that base wireframe as it is. Clearly that wireframe is not how we would be implementing the aesthetics, but it represents where our icons would be, where our photos would be and where our options would be.
The expectation from our UI UX is to have a consistency and hence, every mockup should follow the same base wireframe. From what I can see the upload and the download mockups uploaded recently do not follow this base wireframe.

Again, I am not defending the base wireframe that we have used, clearly as you have mentioned, it has its set of flaws, but due to the time constraint, we decided to go ahead with it.

We are obviously free to update the base later on, but the point right now is that the mockups that we create should have a common base, which the new upload and download dialog clearly don't.

If you feel the base used here is better, again we can update the base for all the UIs later, but for now, I would recommend we follow the same base image to show consistency in our UX.

**Comment by surajp28** [comment]
@ayishacs I believe the look and feel of a UI can be different for everyone. I would have appreciated and worked on your inputs had they been given 3 days ago when the mockups had been posted. In spite of getting reviews on the final day, I worked on the icon size and have made it as requested. Since we have a backup ready for now for such a situation, can we go ahead with that? This would ensure consistency and would follow what was discussed in the meetings?

**Comment by visheshdembla** [comment]
Closing as we are beyond the release deadline and work needs to be done on this. Might need to reopen later.
