### ISSUE TITLE
create a mockup for the upload dialog

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#23]
create a UI mockup for the upload dialog using Adobe XD

**Comment by visheshdembla** [comment]
Added mockups for upload

**Comment by visheshdembla** [comment]
closing as the mockup is uploaded and added to wiki

**Comment by ayishacs** [comment]
![upload](https://user-images.githubusercontent.com/77846296/107160423-b5ebc500-695b-11eb-8424-3eb986d371ac.JPG)
@visheshdembla @surajp28 
Please review the upload page for the application

**Comment by visheshdembla** [comment]
I see the following issues with this mockup.
A. It doesn't follow the template that we have followed for practically every other page we have designed. All the other UIs that we have are in a single harmony so this page should also be in a similar template.
B. Based on the flow diagram that we have drawn and discussed during the meetings, share and upload options are two separate features and merging them was something that wasn't discussed in the meetings before, so the share option doesn't make sense to me here.
C. We do not have an upload feature from IU cloud or any other storage. We only are supposed to have upload from local storage. The only place where we have the IU cloud storage is the download. Again this was discussed in the team meetings and is reflected in the flow diagrams as well. We did not discuss this feature so we should ideally not present this feature in the mock-up.
D. Upload is supposed to be a dialog and not a separate page as mentioned in the issue, which would pop up when we click on the upload button on the view photos page. So we ideally would not have an upload page separately but a dialog that will be shown when you click on the upload button.

I would recommend with the time left we could stick to the version that I have uploaded or you can adopt all the changes and put the same back for review.

**Comment by visheshdembla** [comment]
Please do the needful @ayishacs

**Comment by visheshdembla** [comment]
Closing as we are beyond the release deadline and work needs to be done on this. Might need to reopen later.

**Comment by ayishacs** [comment]
@visheshdembla 
Please find my inputs based on your valuable feedback and suggestions
A. I understand it's important to have uniformity across all the layers in the wireframe. I am glad that the team acknowledges this fact.
B. I have created two separate pages one each for download and upload, share option is about giving access to users and groups for the photos that are being uploaded to the cloud. It is about access management and not about photo sharing. It's been overlooked hence the confusion.
C. Upload feature as seen on the upload page is meant for uploading content to a number of cloud storage provided by IU. Again the details have been overlooked, and assumptions are drawn without observing the details.
D. I have given references in the previous comment that there is no hard and fast rule for it to be a dialog box, it could even be separate pages.

Given the submission deadline and keeping the team's effort in mind. I would like to have my mock-ups as another option with an emphasis on clarity. As we progress, we can eventually make it more user friendly with an elegant design.

I would like to extend my heartfelt thanks to @visheshdembla @surajp28 for being proactively working on the deliverables with constant feedback.

**Comment by visheshdembla** [comment]
Closing as we are beyond the release deadline and work needs to be done on this. Might need to reopen later.
