### ISSUE TITLE
create mockup for Forgot Password Page

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#26]
Create a UI mockup for the forgot password page for the user where the user can navigate if (s)he has forgotten the password for the service.

**Comment by visheshdembla** [comment]
![forget-password-1](https://user-images.githubusercontent.com/13031482/107131452-639b9d00-68a4-11eb-8b15-633a680a63e8.png)
![forget-password-2](https://user-images.githubusercontent.com/13031482/107131453-639b9d00-68a4-11eb-9be7-a5ad1aabc296.png)

**Comment by visheshdembla** [comment]
please have a look at the mockups guys @ayishacs @surajp28

**Comment by surajp28** [comment]
Hi @visheshdembla 
Looks like the color combination for both the diagrams is different. The 'Forgot your password' and 'Reset your password' is different. Also, can you share the color code so that we could have it consistent across all diagrams?

**Comment by visheshdembla** [comment]
closing the issue.
