### ISSUE TITLE
UX design mock ups on pen and paper

### ISSUE THREAD

**Issue by ayishacs** [airavata-courses/Panorama#3]
@visheshdembla @surajp28 @ayishacs
#First deliverable
Task 3: Mock ups for UX design

**Comment by visheshdembla** [comment]
Updated the task to reflect that only Pen-Paper Diagram is expected as part of this task.

**Comment by surajp28** [comment]
Account overview would have hover options with the Panorama photos background
![Accounts_Overview](https://user-images.githubusercontent.com/64825150/106806708-4792c400-6636-11eb-9341-5cab6e1f260c.jpeg)

The delete share and download options shall be highlighted when you click on a single photo or multiple
![delete_share_download](https://user-images.githubusercontent.com/64825150/106806711-482b5a80-6636-11eb-93a0-32db071fe26b.jpeg)

Panorama photos Background
![view_photos](https://user-images.githubusercontent.com/64825150/106806713-482b5a80-6636-11eb-9ea9-799572a1197b.jpeg)

Sign up page
![signup](https://user-images.githubusercontent.com/64825150/106806714-48c3f100-6636-11eb-8c87-3e71b2fcafaf.jpeg)

Login page
![Rename](https://user-images.githubusercontent.com/64825150/106806716-48c3f100-6636-11eb-99f3-dca90b4bb125.jpeg)

The images are rough paper prototypes. Kindly share your inputs on the same @ayishacs @visheshdembla

**Comment by visheshdembla** [comment]
So just to keep it on the record, as of now, we have the following:
1. Login page ✔️ (suraj)
2. Sign up page ✔️ (suraj)
3. Photos Page (when no photo is selected) ✔️ (suraj)
4. Photos Page (when some photos are selected) ✔️ (suraj)
5. Account Overview Page ✔️ (ayisha)
6. Account Options View ✔️(ayisha)
7. Create  Album Page (vishesh)
8. Share Photos/Album Page (vishesh)
9. Download Dialog ✔️ (ayisha)
10. Upload Dialog (add to Account Options) (ayisha)

The mock-up of the pages with ✔️ on pen and paper is done

**Comment by visheshdembla** [comment]
11. Forgot Password (vishesh)

**Comment by surajp28** [comment]
![Panorama](https://user-images.githubusercontent.com/64825150/107005696-19100880-675e-11eb-898f-d46d133ea42c.png)
![Sign up](https://user-images.githubusercontent.com/64825150/107005703-1ad9cc00-675e-11eb-8615-2f2aba8f4290.png)
![Loginpage](https://user-images.githubusercontent.com/64825150/107005715-1e6d5300-675e-11eb-8bc6-5b0cee7da4bd.png)
Hi team,
Kindly review the images and suggest changes.
P.s - One pending

**Comment by visheshdembla** [comment]
@surajp28 would it be possible to have rounded rectangles instead of sharp edges. That is usually considered aesthetically better in UX design. Also, just a suggestion about the Login and Sign-Up. Can we keep the input box design same across both the designs?
For instance, in sign up , there are boxes used for input whereas in Sign-in there is underline on the input.

**Comment by visheshdembla** [comment]
Closing this issue as child issues have been created for each of the UI.

**Comment by ayishacs** [comment]
![BBA69E88-8DBA-43CA-8C02-D4E16206D180](https://user-images.githubusercontent.com/77846296/107148800-cf205180-691a-11eb-8c62-28605e08ed5e.jpeg)

**Comment by ayishacs** [comment]
![26174F29-9760-4EAE-8833-9318A18389E7](https://user-images.githubusercontent.com/77846296/107148813-e8c19900-691a-11eb-9506-4c87b8b146e4.jpeg)

**Comment by ayishacs** [comment]
Upload photos will have similar mockup as download except for upward arrows and upload button.
