### ISSUE TITLE
create project description and update in readme

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#4]
The README file of the project panorama should be updated with the project description along with information about the team.

**Comment by surajp28** [comment]
Hey guys,
Could you review this?
As suggested by @visheshdembla the project description is made from a user point of view.
Any other suggestions?

**Comment by visheshdembla** [comment]
The description has  been adopted as per the feedback. Thanks for the update @surajp28 . I will close the item now, we can revist this if needed later.
