### ISSUE TITLE
Create a database schema for user service

### ISSUE THREAD

**Issue by surajp28** [airavata-courses/Panorama#44]
The issue is created to design a normalized database schema for the application.

**Comment by visheshdembla** [comment]
## Database Schema

1. User
    - ID: UUID
    - username: string
    - email
    - first name
    - last name
    - date of birth
    - gender
    - join date
    - consumption
    - login mechanism (github, google, iu or custom)
2. Image
    - ID: UUID
    - filepath: String
    - creationDateTime: dateTime
    - lastUpdateDateTime: dateTime
    - owner: userID (UUID)
3. Album
    - ID: UUID
    - name: String
    - description: free text
    - owner: userID (UUID)
    - creationDateTime: dateTime
    - lastUpdateDateTime: dateTime
4. AlbumImage*
    - ID: UUID
    - AlbumID: UUID
    - ImageID: UUID
5. Metadata
    - ID: UUID
    - ImageID: UUID
    - MetadataType
    - MetadataValue
6. MetadataType
    - ID: UUID
    - MetadataTypeName
7. Share
    - UUID:
    - shareType: <Album/Image>
    - shareeID: UUID
    - shareItemID: UUID
8. Group
    - ID: UUID
    - Name: String
    - Description: String
9. GroupMember
    - ID: UUID
    - groupID: UUID
    - memberID: userI

**Comment by visheshdembla** [comment]
the only part missing is the Authentication Table
need further investigation and input from teammates evaluating that for designing that table.
