### ISSUE TITLE
Database Technology and Architecture Investigation

### ISSUE THREAD

**Issue by surajp28** [airavata-courses/Panorama#46]
Evaluate if creating database service is the right approach

**Comment by visheshdembla** [comment]
for this issue, 
we evaluated two approaches to database design
a. creating a central database service, that all the other services use to access database
b. let the individual services handle the database requirements themselves

Based on some research off the internet and some self analysis, it seems the first approach takes away from the advantages of using a microservice architecture so we will stick to the second approach.

So the logic to access the database would be encapsulated within the respective services. For milestone we would be using a single shared db instance, which may be change with scale.
