### ISSUE TITLE
Create Architecture Diagram

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Panorama#51]

**Comment by visheshdembla** [comment]
![architecture](https://user-images.githubusercontent.com/13031482/107699864-aedaf480-6c84-11eb-9c07-3babfb56eaa6.png)

**Comment by visheshdembla** [comment]
we need to discuss the overall flow of each and every service. 
I have a rough idea of how this would work, we can discuss this in today's meeting or before the lecture today.
Based on the communication that we architect among the services, we need to design the gRPC exchange formats.

@surajp28 @ayishacs

**Comment by visheshdembla** [comment]
uploading the image for architecture that was left out by mistake.
![architecture](https://user-images.githubusercontent.com/13031482/107703952-76d6b000-6c8a-11eb-93b4-c24c14c99585.png)

**Comment by ayishacs** [comment]
The architecture diagram has covered most of the services we have planned to design and deploy. Good work @visheshdembla
