### ISSUE TITLE
Discuss and decide a release manager for first milestone of the  project

### ISSUE THREAD

**Issue by surajp28** [airavata-courses/Panorama#8]
A release manager would be required for the first milestone of the project. Can we all discuss the same?

**Comment by surajp28** [comment]
I believe to choose the release master in a round-robin fashion. @visheshdembla @ayishacs what do you both think about it?

**Comment by visheshdembla** [comment]
sure. I won't mind going first. Is that fine?

**Comment by ayishacs** [comment]
ya sure.. let's start with vishesh

**Comment by visheshdembla** [comment]
It's decided then!

**Comment by surajp28** [comment]
Great!!
